/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Desktop;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author CLAUDIA NAVARRETE
 */
public class Ejemplo1 extends javax.swing.JInternalFrame {
      boolean runner;
   
    public Ejemplo1() {
        initComponents();
        this.setSize(635,400);
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiCarro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nub = new javax.swing.JLabel();
        piedra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ejercicio 1");
        getContentPane().setLayout(null);

        MiCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro-deportivo.png"))); // NOI18N
        getContentPane().add(MiCarro);
        MiCarro.setBounds(20, 230, 130, 80);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        jButton1.setToolTipText("Inicio");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 10, 40, 39);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reproductor-de-musica.png"))); // NOI18N
        jButton2.setToolTipText("Detener");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 10, 40, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-avance-rapido (1).png"))); // NOI18N
        jButton3.setToolTipText("Continuar");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 10, 40, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-play.png"))); // NOI18N
        jButton4.setToolTipText("Reiniciar");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(570, 10, 40, 40);

        nub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/computacion-en-la-nube.png"))); // NOI18N
        getContentPane().add(nub);
        nub.setBounds(-60, 70, 130, 110);

        piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedras.png"))); // NOI18N
        getContentPane().add(piedra);
        piedra.setBounds(560, 280, 40, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrerasF.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      runner=false;  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     runner= true; 
     Thread Ejercicio1= new Thread(){
           @Override
     public void run(){
       
        int c1=0;
    int nube=0;
        while (runner==true) {
                try {
                    sleep((int)(Math.random()*1000));
                } catch (InterruptedException ex) {
                    Logger.getLogger(Ejemplo1.class.getName()).log(Level.SEVERE, null, ex);
                }
                c1=MiCarro.getLocation().x;
    nube=nub.getLocation().x;  
    nub.setLocation(nub.getLocation().x+10,nub.getLocation().y);
                if(c1<piedra.getLocation().x-10){          
                    MiCarro.setLocation(MiCarro.getLocation().x+10,MiCarro.getLocation().y);
                    repaint();
            }else{break; }
        } 
       }
       };
            Ejercicio1.start();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     runner= false;
       MiCarro.setLocation(0,MiCarro.getLocation().y); 
       nub.setLocation(0,nub.getLocation().y);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     runner= true; 
     Thread Ejercicio1= new Thread(){
           @Override
     public void run(){
       
        int c1=0;
        int nube=0;
        while (runner==true) {
                try {
                    sleep((int)(Math.random()*1000));
                } catch (InterruptedException ex) {
                    Logger.getLogger(Ejemplo1.class.getName()).log(Level.SEVERE, null, ex);
                }
                c1=MiCarro.getLocation().x;
    nube=nub.getLocation().x;  
    nub.setLocation(nub.getLocation().x+10,nub.getLocation().y);
                 
                if(c1<piedra.getLocation().x-10){          
                    MiCarro.setLocation(MiCarro.getLocation().x+10,MiCarro.getLocation().y);
                    repaint();
            }else{break; }
        } 
       }
       };
            Ejercicio1.start();     
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MiCarro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nub;
    private javax.swing.JLabel piedra;
    // End of variables declaration//GEN-END:variables
}
